apiVersion: v1
kind: Service
metadata:
   labels:
      app: dockerapp
   name: dockerapp
spec:
   type: LoadBalancer
   ports:
   -  port: 8069
      targetPort: 8069
   selector:
      app: dockerapp