apiVersion: v1
kind: Service
metadata:
   name: mysql
   labels:
      app: mysql
   name: mysql
spec:
   ports:
   -  name: db-service
      port: 3306
      targetPort: 3306
   selector:
      app: mysql