apiVersion: apps/v1
kind: Deployment
metadata:
   name: mysql
   labels:
      app: mysql
spec:
   replicas: 1
   selector:
      matchLabels:
         app: mysql
   template:
      metadata:
         labels:
            app: mysql
      spec:
         containers:
         -  image: mysql:latest
            name: mysql
            env:
            -  name: MYSQL_USER
               value: root
            -  name: MYSQL_ROOT_PASSWORD
               value: Welcome1
            -  name: MYSQL_PASSWORD
               value: Welcome1
            -  name: MYSQL_DATABASE
               value: root
            ports:
            -  containerPort: 3306
               name: mysql
            volumeMounts:
            -  mountPath: /var/lib/mysql
               name: db-data
         volumes:
         -  name: db-data
            emptyDir: {}